server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost/sarafan
    username: postgres
    password: postgres

  jpa:
    generate-ddl: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    open-in-view: false

  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:session_tables.sql

  config:
    import: file:config/config-security.yml





